import type { Metadata } from "next";
import StyledComponentsRegistry from "../../lib/registry";
import GlobalStyles from "../../../styles/GlobalStyle";
import "../../global.css";

export const metadata: Metadata = {
  title: "Kyle's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
